<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Carbon\Carbon;
use Illuminate\Http\Request;
use PDF;
use Mail;
use DB;

class TestController extends Controller
{

    public function __construct()
    {
    }

    public function mail(Request $request)
    {
        // $order = Order::with('order_detail', 'pickup_order.order_detail_box', 'payment')->findOrFail($order->id);
        $order = ['data' => 'Test ok'];
        $pdf = PDF::loadView('pdf.invoice', $order);
        $pdf->setPaper(array(0, 0, 280, 400), 'portrait');
        $pdf->save('invoice.pdf');
        $message = 'Ok es';

        Mail::send('emails.invoice', $order, function($message) use($order) {
            $message->to('bahtiar@twiscode.com');
            // if($data['cc'] != null){
            //     $message->cc($data['cc']);
            // }
            $message->subject('Test Email');

            //Full path with the pdf name
            $message->attach('invoice.pdf');
        });

    }

    public function exportData()
    {
        $data = [
            ["district_id" => 61,"name" => "GAJAH MENTAH"],
            ["district_id" => 61,"name" => "SEUNEUBOK ACEH"],
            ["district_id" => 61,"name" => "SEUNEUBOK PASE"],
            ["district_id" => 61,"name" => "SUNGAI SIMPANG"],
            ["district_id" => 61,"name" => "PAYA KEUTAPANG"],
            ["district_id" => 61,"name" => "ALUE ITAM"],
            ["district_id" => 61,"name" => "BUKIT DRIEN"],
            ["district_id" => 61,"name" => "BUKIT SELAMAT"],
            ["district_id" => 61,"name" => "KUALA PAREK"],
            ["district_id" => 61,"name" => "LABUHAN KEUDE"],
            ["district_id" => 61,"name" => "KRUENG LINGKA"],
            ["district_id" => 61,"name" => "GEULUMPANG PAYONG"],
            ["district_id" => 61,"name" => "ALUE RANGAN"],
            ["district_id" => 62,"name" => "CEK MBON"],
            ["district_id" => 62,"name" => "SEUNEUBOK PIDIE"],
            ["district_id" => 62,"name" => "KUALA LEUGE"],
            ["district_id" => 62,"name" => "SEUNEUBOK PEUSANGAN"],
            ["district_id" => 62,"name" => "LEUBUK PEMPENG"],
            ["district_id" => 62,"name" => "DAMA TUTONG"],
            ["district_id" => 62,"name" => "BALE BUYA"],
            ["district_id" => 62,"name" => "MATANG GLEUM"],
            ["district_id" => 62,"name" => "ALUE NIBONG"],
            ["district_id" => 62,"name" => "BUKET PALA"],
            ["district_id" => 62,"name" => "BLANG SIMPO"],
            ["district_id" => 62,"name" => "PAYA KALUT"],
            ["district_id" => 62,"name" => "ALUE DUA PAYA GAJAH"],
            ["district_id" => 62,"name" => "SEUNEUBOK ACEH"],
            ["district_id" => 62,"name" => "UTEUN DAMA"],
            ["district_id" => 62,"name" => "PAYA MEULIGO"],
            ["district_id" => 62,"name" => "PUNTI"],
            ["district_id" => 62,"name" => "KEUMUNENG"],
            ["district_id" => 62,"name" => "BANGKA RIMUENG"],
            ["district_id" => 62,"name" => "LEUGE"],
            ["district_id" => 62,"name" => "LHOK DALAM"],
            ["district_id" => 62,"name" => "BANDRONG"],
            ["district_id" => 62,"name" => "TANAH RATA"],
            ["district_id" => 62,"name" => "TUALANG"],
            ["district_id" => 62,"name" => "KEUDE PEUREULAK"],
            ["district_id" => 62,"name" => "COT MUDA ITAM"],
            ["district_id" => 62,"name" => "PASIR PUTIH"],
            ["district_id" => 62,"name" => "BLANG BETRA"],
            ["district_id" => 62,"name" => "BEUSA MEURANOU"],
            ["district_id" => 62,"name" => "SEUMATANG MUDA ITAM"],
            ["district_id" => 62,"name" => "BLANG BALOK"],
            ["district_id" => 62,"name" => "KUALA BUGAK"],
            ["district_id" => 62,"name" => "PAYA LIPAH"],
            ["district_id" => 62,"name" => "COT GEULUMPANG"],
            ["district_id" => 62,"name" => "COT KEH"],
            ["district_id" => 62,"name" => "BLANG BATEE"],
            ["district_id" => 62,"name" => "ALUE RAMBONG"],
            ["district_id" => 62,"name" => "MATANG PEULAWI"],
            ["district_id" => 63,"name" => "BUKIT MEURIAM"],
            ["district_id" => 63,"name" => "SEUNEUBOK PUNTI"],
            ["district_id" => 63,"name" => "ALUE BUGENG"],
            ["district_id" => 63,"name" => "SEUNEUBOK TEUNGOH"],
            ["district_id" => 63,"name" => "SEUNEUBOK TEUPIN"],
            ["district_id" => 63,"name" => "ALUE BU/ALUE LHOK"],
            ["district_id" => 63,"name" => "ALUE GUREP"],
            ["district_id" => 63,"name" => "ALUE BU ALUE NIREH"],
            ["district_id" => 63,"name" => "SEUNEUBOK PAYA"],
            ["district_id" => 63,"name" => "SEUNEUBOK RAWANG"],
            ["district_id" => 63,"name" => "ALUE THO"],
            ["district_id" => 63,"name" => "SEUNEUBOK LAPANG"],
            ["district_id" => 63,"name" => "SEUNEUBOK JALAN"],
            ["district_id" => 63,"name" => "GEULANGGANG MERAK"],
            ["district_id" => 63,"name" => "SEUMATANG KEUDE"],
            ["district_id" => 63,"name" => "BABAH KRUENG"],
            ["district_id" => 63,"name" => "KRUT LINTANG"],
            ["district_id" => 63,"name" => "JEUNGKI"],
            ["district_id" => 63,"name" => "SEUNEUBOK DALAM"],
            ["district_id" => 63,"name" => "TUALANG PATENG"],
            ["district_id" => 64,"name" => "KABU"],
            ["district_id" => 64,"name" => "BEURINGIN"],
            ["district_id" => 64,"name" => "TEUMPEUN"],
            ["district_id" => 64,"name" => "KEBUN TEUMPEUN"],
            ["district_id" => 64,"name" => "PAYA SEUNGAT"],
            ["district_id" => 64,"name" => "TANJUNG TUALANG"],
            ["district_id" => 64,"name" => "BEUSA SEBERANG"],
            ["district_id" => 64,"name" => "PAYA GAJAH"],
            ["district_id" => 64,"name" => "MON GEUDONG"],
            ["district_id" => 64,"name" => "ALUE BU TUHA"],
            ["district_id" => 64,"name" => "ALUE BU JALAN"],
            ["district_id" => 64,"name" => "PAYA BIEK"],
            ["district_id" => 64,"name" => "BEUSA BAROH"],
            ["district_id" => 64,"name" => "ALUE BU TUNONG"],
            ["district_id" => 64,"name" => "ALUE BU JALAN BAROH"],
            ["district_id" => 65,"name" => "BEURANDANG"],
            ["district_id" => 65,"name" => "ALUE GEUNTENG"],
            ["district_id" => 65,"name" => "KLIET"],
            ["district_id" => 65,"name" => "GAMPONG TAMPAK"],
            ["district_id" => 65,"name" => "PAYA PALAS"],
            ["district_id" => 65,"name" => "ALUE BATEE"],
            ["district_id" => 65,"name" => "BHOM LAMA"],
            ["district_id" => 65,"name" => "PASIR PUTIH"],
            ["district_id" => 65,"name" => "ALUE DUA"],
            ["district_id" => 65,"name" => "BUKET PALA BSP"],
            ["district_id" => 65,"name" => "PUNTI PAYONG"],
            ["district_id" => 65,"name" => "SEUMALY"],
            ["district_id" => 65,"name" => "KP. PERTAMINA"],
            ["district_id" => 65,"name" => "BLANG BAROM"],
            ["district_id" => 65,"name" => "PULO BLANG"],
            ["district_id" => 65,"name" => "SNB JOHAN"],
            ["district_id" => 65,"name" => "PAYA UNOU"],
            ["district_id" => 65,"name" => "SNB BARO"],
            ["district_id" => 65,"name" => "SNB DALAM"],
            ["district_id" => 65,"name" => "SEULEMAK MUDA"],
            ["district_id" => 65,"name" => "MATA IE"],
            ["district_id" => 65,"name" => "ALUE UDEP"],
            ["district_id" => 65,"name" => "SEUMANAH JAYA"],
            ["district_id" => 66,"name" => "DAMA PULO"],
            ["district_id" => 66,"name" => "GUREB BLANG"],
            ["district_id" => 66,"name" => "SEUNEUBOK TUTONG"],
            ["district_id" => 66,"name" => "SAM PAI MAH"],
            ["district_id" => 66,"name" => "SEUNEUBOK TUHA"],
            ["district_id" => 66,"name" => "BUKET LANGA"],
            ["district_id" => 66,"name" => "BUKET JUARA"],
            ["district_id" => 66,"name" => "BUKET PALA"],
            ["district_id" => 66,"name" => "MEUNASAH PUUK"],
            ["district_id" => 66,"name" => "KEUDE BLANG"],
            ["district_id" => 66,"name" => "BANTAYAN TIMUR"],
            ["district_id" => 66,"name" => "GAMPONG ACEH"],
            ["district_id" => 66,"name" => "KEUDE ACEH"],
            ["district_id" => 66,"name" => "KUTA BLANG"],
            ["district_id" => 66,"name" => "SEUNEUBOK BACEE"],
            ["district_id" => 66,"name" => "TITI BARO"],
            ["district_id" => 66,"name" => "SEUNEUBOK TEUNGOH (PR)"],
            ["district_id" => 66,"name" => "SEUNEUBOK RAMBONG"],
            ["district_id" => 66,"name" => "TANOH ANOU"],
            ["district_id" => 66,"name" => "KAMPUNG TANJONG"],
            ["district_id" => 66,"name" => "KUALA PD PUNTONG"],
            ["district_id" => 66,"name" => "KAMPUNG JAWA"],
            ["district_id" => 66,"name" => "BLANG GEULUMPANG"],
            ["district_id" => 66,"name" => "GAMPONG JALAN"],
            ["district_id" => 66,"name" => "BUKET MEULINTEUNG"],
            ["district_id" => 66,"name" => "BUKET JOK"],
            ["district_id" => 66,"name" => "TEUPIN BATEE"],
            ["district_id" => 66,"name" => "ALUE DUA MUKA S"],
            ["district_id" => 66,"name" => "TANJONG KAPAI"],
            ["district_id" => 66,"name" => "GAMPONG BARO"],
            ["district_id" => 66,"name" => "KUALA IDI"],
            ["district_id" => 66,"name" => "KEUTAPANG MAMEH"],
            ["district_id" => 66,"name" => "ULEE BLANG"],
            ["district_id" => 66,"name" => "ALUE DUA MUKA 0"],
            ["district_id" => 66,"name" => "KUTA LAWAH"],
            ["district_id" => 67,"name" => "ASAN RAMPAK"],
            ["district_id" => 67,"name" => "BUKET KUTA"],
            ["district_id" => 67,"name" => "BLANG KUTA"],
            ["district_id" => 67,"name" => "ALUE BATEE"],
            ["district_id" => 67,"name" => "PAYA BILI I"],
            ["district_id" => 67,"name" => "BLANG BUKET"],
            ["district_id" => 67,"name" => "KUTA BARO"],
            ["district_id" => 67,"name" => "SEUNEUBOK TEUNGOH"],
            ["district_id" => 67,"name" => "SEUNEUBOK PUNTEUT"],
            ["district_id" => 67,"name" => "SAMA DUA"],
            ["district_id" => 67,"name" => "KAMPUNG KEUDE"],
            ["district_id" => 67,"name" => "MEUNASAH KRUENG"],
            ["district_id" => 67,"name" => "PAYA BILI DUA"],
            ["district_id" => 67,"name" => "PAYA DUA"],
            ["district_id" => 67,"name" => "KAMPUNG KUALA"],
            ["district_id" => 67,"name" => "ALUE IE ITAM"],
            ["district_id" => 67,"name" => "MATANG RAYEUK"],
            ["district_id" => 68,"name" => "SEUNEUBOK BAYU"],
            ["district_id" => 68,"name" => "JAMBO REUHAT"],
            ["district_id" => 68,"name" => "BLANG RAMBONG"],
            ["district_id" => 68,"name" => "ULEE JALAN"],
            ["district_id" => 68,"name" => "SEUNEUBOK KANDANG"],
            ["district_id" => 68,"name" => "SEUNEUBOK BENTENG"],
            ["district_id" => 68,"name" => "SEUNEUBOK PANGOU"],
            ["district_id" => 68,"name" => "URAM JALAN"],
            ["district_id" => 68,"name" => "JALAN DUA"],
            ["district_id" => 68,"name" => "PANTON RAYEUK T"],
            ["district_id" => 68,"name" => "PANTON RAYEUK A"],
            ["district_id" => 68,"name" => "PANTON RAYEUK B"],
            ["district_id" => 68,"name" => "PANTON RAYEUK M"],
            ["district_id" => 68,"name" => "BUKET DRIEN"],
            ["district_id" => 68,"name" => "PAYA LAMAN"],
            ["district_id" => 68,"name" => "SEUNEUBOK SIMPANG"],
            ["district_id" => 69,"name" => "ALUE LHOK"],
            ["district_id" => 69,"name" => "PADANG KASAH"],
            ["district_id" => 69,"name" => "SEUNEUBOK BUYA"],
            ["district_id" => 69,"name" => "PAYA AWE"],
            ["district_id" => 69,"name" => "PAYA GABOH"],
            ["district_id" => 69,"name" => "SEUNEUBOK DRIEN"],
            ["district_id" => 69,"name" => "KEUDE KEUMUNENG"],
            ["district_id" => 69,"name" => "GAMPONG KEUMUNING"],
            ["district_id" => 69,"name" => "SEUNEUBOK MEURUDU"],
            ["district_id" => 69,"name" => "SEUNEUBOK PUNTI"],
            ["district_id" => 69,"name" => "SEUNEUBOK DALAM"],
            ["district_id" => 69,"name" => "SEUNEUBOK JALAN"],
            ["district_id" => 69,"name" => "BUKET TEUKUH"],
            ["district_id" => 69,"name" => "KEUMUNING LHOK"],
            ["district_id" => 69,"name" => "BUKET RUMIYA"],
            ["district_id" => 69,"name" => "ALUE KUMBANG M"],
            ["district_id" => 69,"name" => "ALUE KUMBANG A"],
            ["district_id" => 69,"name" => "SEUNEUBOK BARO"],
            ["district_id" => 69,"name" => "BUKET PUUK"],
            ["district_id" => 69,"name" => "SEUNEUBOK BULOH"],
            ["district_id" => 69,"name" => "BLANG MINJEI"],
            ["district_id" => 69,"name" => "BLANG SEGUCI"],
            ["district_id" => 69,"name" => "BANTAYAN BARAT"],
            ["district_id" => 69,"name" => "SEUNEUBOK TEUPIN PANAH"],
            ["district_id" => 69,"name" => "TEUPIN PANAH"],
            ["district_id" => 70,"name" => "SEUNEUBOK ACEH BARO"],
            ["district_id" => 70,"name" => "LHOK LEUMAK"],
            ["district_id" => 70,"name" => "SEUNEUBOK TEUNGOH (KD II)"],
            ["district_id" => 70,"name" => "MEUNASAH ARON"],
            ["district_id" => 70,"name" => "LHOK DALAM"],
            ["district_id" => 70,"name" => "LHOK MEUREU"],
            ["district_id" => 70,"name" => "PT. MEUREUBO"],
            ["district_id" => 70,"name" => "KHOK PANJOU"],
            ["district_id" => 70,"name" => "ALUE JANGAT"],
            ["district_id" => 70,"name" => "MEDANG ARA"],
            ["district_id" => 70,"name" => "SEUNEUBOK KULAM"],
            ["district_id" => 70,"name" => "GUNONG PUTOH"],
            ["district_id" => 70,"name" => "SEUNEUBOK LAPANG"],
            ["district_id" => 70,"name" => "KEUDE DUA"],
            ["district_id" => 70,"name" => "BUKET PEULAWI"],
            ["district_id" => 70,"name" => "PULO BLANG"],
            ["district_id" => 71,"name" => "KETAPANG DUA"],
            ["district_id" => 71,"name" => "MATANG RAYEUK (SMK)"],
            ["district_id" => 71,"name" => "MENUNASAH JEUMPA"],
            ["district_id" => 71,"name" => "LHOK ASAHAN"],
            ["district_id" => 71,"name" => "TUALANG DALAM"],
            ["district_id" => 71,"name" => "SEUNEUBOK KUYUN"],
            ["district_id" => 71,"name" => "ULEE GLE"],
            ["district_id" => 71,"name" => "SEUNEUBOK BARAT"],
            ["district_id" => 71,"name" => "SEUNEUBOK TEUNGOH (SMK)"],
            ["district_id" => 71,"name" => "SEUNEUBOK TIMUR"],
            ["district_id" => 71,"name" => "MATANG BUNGONG"],
            ["district_id" => 71,"name" => "MATANG RAYEUK (PR)"],
            ["district_id" => 71,"name" => "SEUNEUBOK DALAM (SMK)"],
            ["district_id" => 72,"name" => "SEUNEUBOK SIMPANG"],
            ["district_id" => 72,"name" => "ALUR LHOK"],
            ["district_id" => 72,"name" => "ALUR MERBO"],
            ["district_id" => 72,"name" => "MEUNASAH KEUTAPANG"],
            ["district_id" => 72,"name" => "ALUE DALAM"],
            ["district_id" => 72,"name" => "DAMA POLO II"],
            ["district_id" => 72,"name" => "ALUR LUDIN II"],
            ["district_id" => 72,"name" => "JUNGKA GAJAH"],
            ["district_id" => 72,"name" => "BUKET RUMIYA"],
            ["district_id" => 72,"name" => "BUKET RAYA"],
            ["district_id" => 72,"name" => "GASEH SAYANG"],
            ["district_id" => 72,"name" => "SEUNEUBOK BULOH"],
            ["district_id" => 72,"name" => "KAPAI BARO"],
            ["district_id" => 72,"name" => "KEMUNING I"],
            ["district_id" => 72,"name" => "SEUNEUBOK TUHA I"],
            ["district_id" => 72,"name" => "ALUE GADENG"],
            ["district_id" => 72,"name" => "TRIENG GADENG"],
            ["district_id" => 72,"name" => "BUKET KULAM"],
            ["district_id" => 72,"name" => "SEUNEUBOK TEUNGOH"],
            ["district_id" => 72,"name" => "DAMA PULO I"],
            ["district_id" => 72,"name" => "KAMPUNG BEUNOT"],
            ["district_id" => 72,"name" => "TEUPIN DRUM"],
            ["district_id" => 72,"name" => "KUALA IDI CUT"],
            ["district_id" => 72,"name" => "KAMPUNG BARO"],
            ["district_id" => 72,"name" => "ALUR LUDIN I"],
            ["district_id" => 72,"name" => "LHOK GEULUMPANG"],
            ["district_id" => 72,"name" => "BLANG BUKET"],
            ["district_id" => 72,"name" => "SEUNEUBOK TUHA II"],
            ["district_id" => 72,"name" => "KEMUNING II"],
            ["district_id" => 72,"name" => "BUKET TUALANG"],
            ["district_id" => 72,"name" => "BAGOK PANAH IV"],
            ["district_id" => 72,"name" => "BAGOK PANAH III"],
            ["district_id" => 72,"name" => "KEMUNING  V"],
            ["district_id" => 72,"name" => "KEMUNING III"],
            ["district_id" => 72,"name" => "KEMUNING IV"],
            ["district_id" => 72,"name" => "GRONG-GRONG"],
            ["district_id" => 72,"name" => "KAMPUNG KEUDE"],
            ["district_id" => 72,"name" => "KEUDE IDI CUT"],
            ["district_id" => 72,"name" => "SEUNEUBOK BAROH"],
            ["district_id" => 72,"name" => "MEUNASAH BLANG"],
            ["district_id" => 72,"name" => "SEUNEUBOK ACEH"],
            ["district_id" => 72,"name" => "MATANG GEUTOU"],
            ["district_id" => 72,"name" => "MATANG PINEUNG"],
            ["district_id" => 72,"name" => "BAGOK PANAH I"],
            ["district_id" => 72,"name" => "BAGOK PANAH II"],
            ["district_id" => 73,"name" => "ALUE SIWAH SERDANG"],
            ["district_id" => 73,"name" => "GAMPONG LHEE"],
            ["district_id" => 73,"name" => "BEURANDANG"],
            ["district_id" => 73,"name" => "SEUNEUBOK RAMBONG"],
            ["district_id" => 73,"name" => "GAMPUNG JALAN"],
            ["district_id" => 73,"name" => "BUKET MEURAK"],
            ["district_id" => 73,"name" => "SEUNEUBOK DALAM"],
            ["district_id" => 73,"name" => "KAMPUNG MESJID"],
            ["district_id" => 73,"name" => "PAYA ENJEE"],
            ["district_id" => 73,"name" => "SEULEUMAK MUDA"],
            ["district_id" => 73,"name" => "COT ASAN"],
            ["district_id" => 73,"name" => "BUKET PANYANG"],
            ["district_id" => 73,"name" => "BUKET PANJOU"],
            ["district_id" => 73,"name" => "MATANG PANYANG"],
            ["district_id" => 73,"name" => "MEUNASAH HAGU"],
            ["district_id" => 73,"name" => "MATANG KUNYET"],
            ["district_id" => 73,"name" => "MATANG NEUHEUN"],
            ["district_id" => 73,"name" => "TEUPIN PUKAT"],
            ["district_id" => 73,"name" => "PULO-U"],
            ["district_id" => 73,"name" => "MATANG SEULEUMAK"],
            ["district_id" => 73,"name" => "BANTAYAN"],
            ["district_id" => 73,"name" => "BLANG PANJOU"],
            ["district_id" => 73,"name" => "SEUMATANG ARON"],
            ["district_id" => 73,"name" => "MEUDANG ARA"],
            ["district_id" => 73,"name" => "MEUNASAH TEUNGOH"],
            ["district_id" => 73,"name" => "KAMPUNG KEUDE BAGOK DUA"],
            ["district_id" => 73,"name" => "KAMPUNG KEUDE BAGOK SA"],
            ["district_id" => 73,"name" => "KUALA BAGOK"],
            ["district_id" => 73,"name" => "ASAN TANJUNG"],
            ["district_id" => 73,"name" => "BAROH BUGENG"],
            ["district_id" => 73,"name" => "PEULAWI"],
            ["district_id" => 74,"name" => "TUNONG BUGENG"],
            ["district_id" => 74,"name" => "GAMPONG CEMPEUDAK"],
            ["district_id" => 74,"name" => "BUKET TUFAH"],
            ["district_id" => 74,"name" => "TUNONG ULEE GAJAH"],
            ["district_id" => 74,"name" => "KEUDONDONG"],
            ["district_id" => 74,"name" => "SEUNEUBOK PANTON"],
            ["district_id" => 74,"name" => "BUKET TEUMPEN"],
            ["district_id" => 74,"name" => "KEUDE BLANG"],
            ["district_id" => 74,"name" => "PAYA KREUB"],
            ["district_id" => 74,"name" => "TUNONG PAYA KREUB"],
            ["district_id" => 74,"name" => "ALUE SIWAH DUA"],
            ["district_id" => 75,"name" => "KEUMUNENG"],
            ["district_id" => 75,"name" => "LADANG BARO"],
            ["district_id" => 75,"name" => "SEUNEUBOK BARO"],
            ["district_id" => 75,"name" => "SEUNEUBOK RAMBONG"],
            ["district_id" => 75,"name" => "TEUPIN RAYA"],
            ["district_id" => 75,"name" => "BUKET PANYANG"],
            ["district_id" => 75,"name" => "BLANG KEUMUHANG"],
            ["district_id" => 75,"name" => "BUKIT MAKMUR"],
            ["district_id" => 75,"name" => "BUKET DINDENG"],
            ["district_id" => 75,"name" => "LHOK RAMBONG"],
            ["district_id" => 75,"name" => "BLANG MIDEUN"],
            ["district_id" => 75,"name" => "BLANG JAMBEE"],
            ["district_id" => 75,"name" => "PAYA BAKONG"],
            ["district_id" => 75,"name" => "BUKET SERAJA"],
            ["district_id" => 75,"name" => "BLANG PAOH SATU"],
            ["district_id" => 75,"name" => "ULEE ATEUNG"],
            ["district_id" => 75,"name" => "MANE RAMPAK"],
            ["district_id" => 75,"name" => "UJONG TUNONG"],
            ["district_id" => 75,"name" => "PAYA PASI"],
            ["district_id" => 75,"name" => "BLANG GLEUM"],
            ["district_id" => 75,"name" => "ALUE CEK DOY"],
            ["district_id" => 75,"name" => "TUMPOK TEUNGOH"],
            ["district_id" => 75,"name" => "MATANG"],
            ["district_id" => 75,"name" => "JULOK TUNONG"],
            ["district_id" => 75,"name" => "BLANG PAOH DUA"],
            ["district_id" => 75,"name" => "KEUDE KUTA BINJAI"],
            ["district_id" => 75,"name" => "ULEE TANOH"],
            ["district_id" => 75,"name" => "KUALA GEULUMPANG"],
            ["district_id" => 75,"name" => "BLANG UYOK"],
            ["district_id" => 75,"name" => "ULEE BLANG"],
            ["district_id" => 75,"name" => "NALEUNG"],
            ["district_id" => 75,"name" => "LABOHAN"],
            ["district_id" => 75,"name" => "GAMPONG BARO"],
            ["district_id" => 75,"name" => "SEUMATANG"],
            ["district_id" => 75,"name" => "TANJONG TOK BLANG"],
            ["district_id" => 75,"name" => "SIMPANG LHEE"],
            ["district_id" => 75,"name" => "LHOK SEUNTANG"],
            ["district_id" => 76,"name" => "ALUE IE ITAM"],
            ["district_id" => 76,"name" => "SEUNEUBOK BAYU"],
            ["district_id" => 76,"name" => "BLANG NISAM"],
            ["district_id" => 76,"name" => "BANDAR BARO"],
            ["district_id" => 76,"name" => "ALUE PATONG"],
            ["district_id" => 76,"name" => "SEUNEUBOK CINA"],
            ["district_id" => 76,"name" => "PELITA SAGUP JAYA"],
            ["district_id" => 76,"name" => "PERK JULOK RAYEUK UTARA"],
            ["district_id" => 76,"name" => "PERK JULOK RAYEUK SELATAN"],
            ["district_id" => 76,"name" => "JAMBO BALEE"],
            ["district_id" => 76,"name" => "ALUE IE MIRAH"],
            ["district_id" => 76,"name" => "JAMBO LUBOK"],
            ["district_id" => 76,"name" => "SUKA MAKMUR"],
            ["district_id" => 77,"name" => "BLANG SEUNONG"],
            ["district_id" => 77,"name" => "PANTE LABU"],
            ["district_id" => 77,"name" => "PANTE RAMBONG"],
            ["district_id" => 77,"name" => "ALUE IE MIRAH"],
            ["district_id" => 77,"name" => "SEUNEUBOK TUHA"],
            ["district_id" => 77,"name" => "SEUNEUBOK SABOH"],
            ["district_id" => 77,"name" => "BUKET KARENG"],
            ["district_id" => 77,"name" => "BUKET BATA"],
            ["district_id" => 77,"name" => "GRONG GRONG"],
            ["district_id" => 77,"name" => "MEUNASAH TUNONG"],
            ["district_id" => 77,"name" => "MATANG PEUREULAK"],
            ["district_id" => 77,"name" => "MEUNASAH LEUBOK"],
            ["district_id" => 77,"name" => "MEUNASAH TEUNGOH"],
            ["district_id" => 77,"name" => "KEUDE BARO"],
            ["district_id" => 77,"name" => "PANTE PANAH"],
            ["district_id" => 77,"name" => "MATANG PUDENG"],
            ["district_id" => 77,"name" => "GAMPONG PUTOH DUA"],
            ["district_id" => 77,"name" => "MATANG KRUET"],
            ["district_id" => 77,"name" => "PAYA DEUMAM SATU"],
            ["district_id" => 77,"name" => "PAYA DEUMAM LHEE"],
            ["district_id" => 77,"name" => "PAYA DEUMAM DUA"],
            ["district_id" => 77,"name" => "PUTOH SATU"],
            ["district_id" => 77,"name" => "SUKA DAMAI"],
            ["district_id" => 77,"name" => "SAH RAJA"],
            ["district_id" => 77,"name" => "SIJUDO"],
            ["district_id" => 78,"name" => "MATANG WENG"],
            ["district_id" => 78,"name" => "ALUE MULIENG"],
            ["district_id" => 78,"name" => "PUCOK ALUE BARAT"],
            ["district_id" => 78,"name" => "PUCOK ALUE SATU"],
            ["district_id" => 78,"name" => "MATANG KUMBANG"],
            ["district_id" => 78,"name" => "TITI BAROEH"],
            ["district_id" => 78,"name" => "ARA KUNDO"],
            ["district_id" => 78,"name" => "ALUE BULOH DUA"],
            ["district_id" => 78,"name" => "MATANG RAYEUK"],
            ["district_id" => 78,"name" => "TEUPIN BREUH"],
            ["district_id" => 78,"name" => "BLANG ME"],
            ["district_id" => 78,"name" => "PUCOK ALUE DUA"],
            ["district_id" => 78,"name" => "PEULALU"],
            ["district_id" => 78,"name" => "ALUE BULOH SATU"],
            ["district_id" => 78,"name" => "KUALA SIMPANG ULIM"],
            ["district_id" => 78,"name" => "KAMPONG BARO"],
            ["district_id" => 78,"name" => "NICAH AWE"],
            ["district_id" => 78,"name" => "BANTAYAN"],
            ["district_id" => 78,"name" => "KEUDE TUHA"],
            ["district_id" => 78,"name" => "GAMPONG BLANG"],
            ["district_id" => 78,"name" => "LAMPUH RAYEUK"],
            ["district_id" => 78,"name" => "TEUPIN MAMPLAM"],
            ["district_id" => 78,"name" => "MATANG SEUPENG"],
            ["district_id" => 79,"name" => "PAYA DEUMAM PEUT"],
            ["district_id" => 79,"name" => "PAYA NADEN"],
            ["district_id" => 79,"name" => "TANJUNG ARA"],
            ["district_id" => 79,"name" => "TANJUNG MINJEI"],
            ["district_id" => 79,"name" => "SEUNEUBOK PIDIE"],
            ["district_id" => 79,"name" => "RAMBONG LOP"],
            ["district_id" => 79,"name" => "MATANG JROK"],
            ["district_id" => 79,"name" => "MATANG NIBONG"],
            ["district_id" => 79,"name" => "MADAT"],
            ["district_id" => 79,"name" => "ABEUK GEULANTEU"],
            ["district_id" => 79,"name" => "MATANG KEUPULA SATU"],
            ["district_id" => 79,"name" => "ULEE ATEUNG"],
            ["district_id" => 79,"name" => "BLANG ANDAM"],
            ["district_id" => 79,"name" => "BINTAH"],
            ["district_id" => 79,"name" => "BLANG AWE"],
            ["district_id" => 79,"name" => "PANTE MEUREUBO"],
            ["district_id" => 79,"name" => "LUENG SATU"],
            ["district_id" => 79,"name" => "MATANG KEUPULA LHEE"],
            ["district_id" => 79,"name" => "MATANG KEUPULA DUA"],
            ["district_id" => 79,"name" => "BLANG UBIT"],
            ["district_id" => 79,"name" => "LUENG PEUT"],
            ["district_id" => 79,"name" => "LUENG DUA"],
            ["district_id" => 79,"name" => "MATANG GURU"],
            ["district_id" => 79,"name" => "PANTE BAYAM"],
            ["district_id" => 79,"name" => "MEUNASAH TINGKEUM"],
            ["district_id" => 79,"name" => "MEUNASAH ASAN"],
            ["district_id" => 80,"name" => "LUMUT"],
            ["district_id" => 80,"name" => "DELUNG SEKINEL"],
            ["district_id" => 80,"name" => "JAMAT"],
            ["district_id" => 80,"name" => "LINGE"],
            ["district_id" => 80,"name" => "OWAQ"],
            ["district_id" => 80,"name" => "PENARUN"],
            ["district_id" => 80,"name" => "UMANG"],
            ["district_id" => 80,"name" => "SIMPANG TIGA UNING"],
            ["district_id" => 80,"name" => "PANTAN NANGKA"],
            ["district_id" => 80,"name" => "MUNGKUR"],
            ["district_id" => 80,"name" => "GEWAT"],
            ["district_id" => 80,"name" => "KEMERLENG"],
            ["district_id" => 80,"name" => "KUTE RAYANG"],
            ["district_id" => 80,"name" => "KUTE KERAMIL"],
            ["district_id" => 80,"name" => "KUTE RIYEM"],
            ["district_id" => 80,"name" => "KUTE BARU"],
            ["district_id" => 80,"name" => "KUTE ROBEL"],
            ["district_id" => 80,"name" => "GELAMPANG GADING"],
            ["district_id" => 80,"name" => "GEMBOYAH"],
            ["district_id" => 80,"name" => "DISPOT LINGE"],
            ["district_id" => 80,"name" => "ISE-ISE"],
            ["district_id" => 80,"name" => "KUTE REJE"],
            ["district_id" => 80,"name" => "REJE PAYUNG"],
            ["district_id" => 80,"name" => "ARUL ITEM"],
            ["district_id" => 80,"name" => "ANTARA"],
            ["district_id" => 80,"name" => "PANTAN REDUK"]
        ];
        $datajson = [];
        // for ($i=997; $i < 1000; $i++) {
        //     //$datajson[$i] = ["regency_id" => $data[$i]['regency_id'],"name" => $data[$i]['name']];
        //     DB::table('districts')->insert(["regency_id" => $data[$i]['regency_id'],"name" => $data[$i]['name']]);
        // }
        foreach ($data as $k => $v) {
            if($k < 550){
                DB::table('villages')->insert(["district_id" => $v['district_id'],"name" => $v['name']]);
            }
        }

        return response()->json([
            'status' => true,
            'message' => 'Your order has been made. Please complete the payment within 24 hours.',
            'count' => count($data),
            'data' => $data
        ]);
    }

}
